name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: 0.1.4
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: |
            3.1.x
            6.0.x

      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget

      - name: Build
        run: dotnet build src/gen/src/Apideck/Apideck.csproj --configuration Release

      - name: Package
        run: dotnet pack -c Release -o . src/gen/src/Apideck/Apideck.csproj

      - name: Publish
        run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: ${{ env.PACKAGE_VERSION }}
